name: Release to dockerhub

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
    login:
      runs-on: ubuntu-latest
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: sweagent
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Run release script
          run: ./release_dockerhub.sh sweagent latest